basePath: /api/v1
definitions:
  config.ConfigType:
    properties:
      context:
        type: string
      name:
        type: string
      version:
        type: string
    type: object
  ex.Response:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact:
    email: hohice@163.com
    name: hohice
    url: https://github.com/hohice
  description: Gin Web API server starter.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ginS
  version: 1.0.0
paths:
  /config:
    post:
      consumes:
      - application/json
      description: Modify Application Config
      parameters:
      - description: data of the config
        in: body
        name: config
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "400":
          description: Invalid Name supplied!
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "404":
          description: Instance not found
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "405":
          description: Invalid input
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
      tags:
      - config
    put:
      consumes:
      - application/json
      description: Modify Application Config
      parameters:
      - description: data of the config
        in: body
        name: config
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "400":
          description: Invalid Name supplied!
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "404":
          description: Instance not found
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "405":
          description: Invalid input
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
      tags:
      - config
  /config/name/{name}/version/{version}:
    delete:
      consumes:
      - application/json
      description: Delete Application Config
      parameters:
      - description: name of the config
        in: path
        name: name
        required: true
        type: string
      - description: version of the config
        in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "400":
          description: Invalid Name supplied!
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "404":
          description: Instance not found
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "405":
          description: Invalid input
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
      tags:
      - config
    get:
      consumes:
      - application/json
      description: Get Application Config
      parameters:
      - description: name of the config
        in: path
        name: name
        required: true
        type: string
      - description: version of the config
        in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/config.ConfigType'
            type: object
        "400":
          description: Invalid Name supplied!
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "404":
          description: Instance not found
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "405":
          description: Invalid input
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
      tags:
      - config
  /test/start/name/{name}/version/{version}:
    post:
      consumes:
      - application/json
      description: Modify Application Config
      parameters:
      - description: name of the config
        in: path
        name: name
        required: true
        type: string
      - description: version of the config
        in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "400":
          description: Invalid Name supplied!
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "404":
          description: Instance not found
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "405":
          description: Invalid input
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/ex.Response'
            type: object
      tags:
      - config
swagger: "2.0"
