/*
 * walm
 *
 * warp application lifecycle manager
 *
 * API version: 1.0.0
 * Contact: bing.han@transwarp.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ex

type Response struct {
	Code    int    `json:"code,omitempty" description:"code of the response"`
	Message string `json:"message,omitempty" description:"message of the response"`
}

func ReturnBadRequest() (int, Response) {
	ar := Response{
		Code:    INVALID_PARAMS,
		Message: GetMsg(INVALID_PARAMS),
	}
	return INVALID_PARAMS, ar
}

func ReturnInternalServerError(err error) (int, Response) {
	ar := Response{
		Code:    INTERNAL_ERROR,
		Message: GetMsg(INTERNAL_ERROR),
	}
	return INTERNAL_ERROR, ar
}

func ReturnClusterExistError() (int, Response) {
	ar := Response{
		Code:    ERROR_CLUSTER_EXIST,
		Message: GetMsg(ERROR_CLUSTER_EXIST),
	}
	return ERROR_CLUSTER_EXIST, ar
}

func ReturnClusterNotExistError() (int, Response) {
	ar := Response{
		Code:    ERROR_CLUSTER_NOT_EXIST,
		Message: GetMsg(ERROR_CLUSTER_NOT_EXIST),
	}
	return ERROR_CLUSTER_NOT_EXIST, ar
}

func ReturnOK() (int, Response) {
	ar := Response{
		Code:    SUCCESS,
		Message: GetMsg(SUCCESS),
	}
	return SUCCESS, ar
}
